set -g @thm_bg "#1a1b26"
set -g @thm_blue "#7aa2f7"
set -g @thm_green "#9ece6a"
set -g @thm_yellow "#e0af68"
set -g @thm_red "#f7768e"
set -g @thm_rosewater "#c0caf5"
set -g @thm_overlay_0 "#414868"
set -g @thm_overlay_1 "#565f89"
